project:
  type: website

website:
  title: "Michal Kvasnička"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: teaching.qmd
        text: Teaching

format:
  html:
    # theme: cosmo
    theme: 
      dark: darkly
      light: flatly
    css: styles.css
    page-layout: full
    # toc: true



